### ISSUE TITLE
Treat .npmignore as .gitignore

### ISSUE THREAD

**Issue by XDex** [SBoudrias/gulp-exclude-gitignore#3]
I'm having an issue with a Yeoman generator - on Node/npm version 5.x **.gitignore** files are automatically renamed to **.npmignore** (see [this npm issue](https://github.com/npm/npm/issues/1862))
Because of this, my gulp tasks fail when using gulp-exclude-gitignore with:

```
Error: ENOENT: no such file or directory, open '/Users/andrei/dev/exttmp/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at module.exports (/Users/andrei/dev/exttmp/node_modules/gulp-exclude-gitignore/lib/index.js:17:21)
    at Gulp.<anonymous> (/Users/andrei/dev/exttmp/gulpfile.js:17:11)
    at module.exports (/Users/andrei/dev/exttmp/node_modules/orchestrator/lib/runTask.js:34:7)
...
```

**Comment by XDex** [comment]
Could you please fix this, so that **.npmignore** will be used in case when **.gitignore** is not found?
Thanks!

**Comment by SBoudrias** [comment]
I don't understand how this is impacting you.

The renaming is only done inside packaged modules.

**Comment by SBoudrias** [comment]
Closing for lack of activity.
